sudo: required

services:
  - docker

before_script:
  - docker-compose -f docker-compose.dev.yml up --build -d
  
script:
  - npm run lint
  - npm run test

after_success:
  - npm run exit

after_failure:
  - npm run exit