version: '3'
services:

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '9000:9000'
    external_links:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'