version: '3.1'
services:
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "9000:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  app:
    env_file: 
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - ./:/app
      - /app/node_modules
    command: ["npm", "run", "start"]

  mongo:
    image: mongo
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes: 
     - mongo-db:/data/db

volumes: 
  mongo-db: