version: '3'

services: 
  mongo:
    image: mongo
    volumes: 
      - ./data:/data/db
    ports: 
      - "27017:27017"

  server:
    depends_on: 
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '9000'
    ports:
      - '9000:9000'
    command: npm run start