version: '3'
services:
  api:
    env_file: 
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/app
      - /app/node_modules
    depends_on: 
      - mongo
    command: npm run start
    
  mongo:
    image: mongo
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes: 
     - mongo-db:/data/db

volumes: 
  mongo-db: