version: '3'
services:

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '9000:9000'
    external_links:
      - mongo
    command: ["npm", "run", "start"]

  mongo:
    image: mongo
    ports:
      - '27017:27017'
  
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test"]
  
  lint:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "lint"]
