version: '3'
services:
  mongoTest:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  lint:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run lint

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run test
    depends_on: 
        - mongoTest
    environment: 
      - PORT=${PORT}
      - BASE_URL=${BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_IP=${MONGO_IP}
      - MONGO_PORT=${MONGO_PORT}