version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "3000:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  api:
    env_file: 
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./:/app
      - /app/node_modules
    depends_on: 
      - mongo
    command: npm run start
    
  mongo:
    image: mongo
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes: 
     - mongo-db:/data/db

volumes: 
  mongo-db: