version: '3'
services:
  mongoTest:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  lint:
    build:
      context: .
      dockerfile: Dockerfile
      command: npm run lint

  test:
    build:
      context: .
      dockerfile: Dockerfile
      command: npm run test
      depends_on: 
        - mongoTest