version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - '9000:9000'
    external_links:
      - mongo
    command: npm run start
  mongo:
    image: mongo
    ports:
      - '27017:27017'